import numpy as np
import matplotlib.pyplot as plt
from sympy import sqrt,symbols,simplify,diff,lambdify,solve
plt.close('all')
x,y = symbols('x y')
F= 13*x**2 +18*x*y + 37*y**2 - 26*x-18*y+3
Fx=simplify(diff(F,x))
Fy=simplify(diff(F,y))
Fim=lambdify((x,y),F,'numpy')
xl = np.linspace(-1, 3, 31)
yl = np.linspace(-2, 2, 31)
X, Y = np.meshgrid(xl, yl)
Z=Fim(X,Y)
fig, ax = plt.subplots(1, 1)
ax.contourf(X,Y,Z,[0,Fim(0,0)], colors='c',extend='min')
ax.contour(X,Y,Z,[3], colors='k',linewidths=4)
ax.axis('equal')
x0=0.1
yr=solve(F.subs(x,x0),y)
y0=yr[0]
print('y0=',y0)
ax.scatter(x0,y0,s=100,c='r')
Fx0=Fx.subs([(x,x0),(y,y0)])
Fy0=Fy.subs([(x,x0),(y,y0)])
eqt=Fx0*(x-x0)+Fy0*(y-y0)
eqn=Fx0*(y-y0)-Fy0*(x-x0)
Eqt=lambdify((x,y),eqt,'numpy')
Eqn=lambdify((x,y),eqn,'numpy')
Zt=Eqt(X,Y)
Zn=Eqn(X,Y)
ax.contour(X,Y,Zt,[0],colors='r',linewidths=2, linestyles='dashed')
ax.contour(X,Y,Zn,[0], colors='b',linewidths=2,linestyles='dashdot')

x0=1
yr=solve(F.subs(x,x0),y)
y0=yr[0]
print('y0=',y0)
ax.scatter(x0,y0,s=100,c='r')
Fx0=Fx.subs([(x,x0),(y,y0)])
Fy0=Fy.subs([(x,x0),(y,y0)])
eqt=Fx0*(x-x0)+Fy0*(y-y0)
eqn=Fx0*(y-y0)-Fy0*(x-x0)
Eqt=lambdify((x,y),eqt,'numpy')
Eqn=lambdify((x,y),eqn,'numpy')
Zt=Eqt(X,Y)
Zn=Eqn(X,Y)
ax.contour(X,Y,Zt,[0],colors='r',linewidths=2, linestyles='dashed')
ax.contour(X,Y,Zn,[0], colors='b',linewidths=2,linestyles='dashdot')

x0=0.1
yr=solve(F.subs(x,x0),y)
y0=yr[1]
print('y0=',y0)
ax.scatter(x0,y0,s=100,c='r')
Fx0=Fx.subs([(x,x0),(y,y0)])
Fy0=Fy.subs([(x,x0),(y,y0)])
eqt=Fx0*(x-x0)+Fy0*(y-y0)
eqn=Fx0*(y-y0)-Fy0*(x-x0)
Eqt=lambdify((x,y),eqt,'numpy')
Eqn=lambdify((x,y),eqn,'numpy')
Zt=Eqt(X,Y)
Zn=Eqn(X,Y)
ax.contour(X,Y,Zt,[0],colors='r',linewidths=2, linestyles='dashed')
ax.contour(X,Y,Zn,[0], colors='b',linewidths=2,linestyles='dashdot')

x0=1
yr=solve(F.subs(x,x0),y)
y0=yr[1]
print('y0=',y0)
ax.scatter(x0,y0,s=100,c='r')
Fx0=Fx.subs([(x,x0),(y,y0)])
Fy0=Fy.subs([(x,x0),(y,y0)])
eqt=Fx0*(x-x0)+Fy0*(y-y0)
eqn=Fx0*(y-y0)-Fy0*(x-x0)
Eqt=lambdify((x,y),eqt,'numpy')
Eqn=lambdify((x,y),eqn,'numpy')
Zt=Eqt(X,Y)
Zn=Eqn(X,Y)
ax.contour(X,Y,Zt,[0],colors='r',linewidths=2, linestyles='dashed')
ax.contour(X,Y,Zn,[0], colors='b',linewidths=2,linestyles='dashdot')
